# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               DōsLambōs
tagline:             'Music, Art'
description:         'We make music.  We draw.  We sing, we are.'
url:                 http://doslambos.github.io
baseurl:             'http://doslambos.github.io'

# About/contact
author:
  name:              Diwant Vaidya
  url:               https://twitter.com/doslambos
  email:             team@doslambos.com

# Pagination
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# Custom vars
version:             1.0.0
